name: expense_repository 
description: The Repo that handles expenses

publish_to: 'none' 


environment: 
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.9
  # rxdart: ^0.28.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


  uses-material-design: true